### ISSUE TITLE
SHAdataset process typo

### ISSUE THREAD

**Issue by RyougiKukoc** [cha15yq/CUT#2]
The paper says you limit the longer side of each image with 1920 pixels, so I suppose 
[preprocess_dataset_SHA.py#L46](https://github.com/cha15yq/CUT/blob/main/preprocess_dataset_SHA.py#L46) should be 
`elif im_w > max_size:`
and [preprocess_dataset_SHA.py#L57](https://github.com/cha15yq/CUT/blob/main/preprocess_dataset_SHA.py#L57) should be
`elif im_h > max_size:`

The corresponding code in preprocess_dataset_QNRF.py is right.

**Comment by cha15yq** [comment]
Thanks for pointing out this problem!
