### ISSUE TITLE
How can I test the model on a single image?

### ISSUE THREAD

**Issue by TheSenPie** [cha15yq/CUT#3]
Hi, how can I use your model to process single image? My use case is, I would provide a single image to the program and it would output me the count of people in that image. Maybe you have an existing script, that just does that?

For example, I would give it this picture:
![image](https://github.com/cha15yq/CUT/assets/20699484/fe5f3c43-4268-4498-ad9f-981cfd6bd939)

And it would output number 24.

Thanks.

**Comment by cha15yq** [comment]
Hi there, I didn't preserve the visualization code. However, you can achieve that by modifying the test.py.
